---
- hosts: [all]
  sudo: yes
  tags: ['system']
  pre_tasks:
#    - name: Install Debian Packages
#      apt: pkg={{ item }} state=present update_cache=yes
#      with_items:
#        - git
#        - vim
#        - htop
#        - unzip
#      when: ansible_os_family == "Debian"
#
#    - name: set time
#      sudo: yes
#      command: ntpd -q
#
    - name: Downloading and enable the EPEL repository definitions.
      yum: name=http://download.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
      when: ansible_os_family == "RedHat"

    - name: Install Redhat Packages
      yum: pkg={{ item }} state=present
      with_items:
        - git
        - vim
        - htop
        - unzip
      when: ansible_os_family == "RedHat"

    - name: Disable iptables
      action: service name=iptables state=stopped enabled=false
      when: ansible_os_family == "RedHat"

    - name: Remove require tty
      lineinfile: regexp="^\s+\w+\s+requiretty" dest=/etc/sudoers state=absent

    - name: Remove require tty - alt
      lineinfile: regexp="requiretty" dest=/etc/sudoers.d/os_defaults state=absent

#  tasks:
#    - cron: name="update time on reboot" special_time=reboot job="ntpd -q >/dev/null 2>&1"
#    - cron: name="update time hourly" special_time=hourly job="ntpd -q >/dev/null 2>&1"
