---
- hosts: [nimbus]
  sudo: True
  roles:
    - { role: 'ansible-mesos-storm', storm_nimbus_enabled: true, storm_supervisor_enabled: true, zookeeper_hosts: "{{ groups.mesos_primaries | join(':2181,') }}:2181", nimbus_host: "{{ groups.nimbus[0] }}" }
