---
- hosts: [nimbus]
  sudo: True
  roles:
    - { role: 'ansible-mesos-storm', storm_nimbus_enabled: true, storm_supervisor_enabled: false, zookeeper_hosts: "{{ groups.mesos_primaries | join(':2181,') }}:2181", nimbus_host: "{{ groups.nimbus[0] }}" }
- hosts: [mesos_workers]
  sudo: True
  tasks:
    - group: name=storm
    - user: name=storm groups=storm
    - file: path=/var/log/storm state=directory owner=storm group=storm
    - file: path=/var/storm state=directory owner=storm group=storm
